Repository bounswe/bounswe2018group4, pull requests merged in 2018-12, with the labels that each got.

#129 Android/bug memory list
  memorist-android/app/src/main/java/com/memorist/memorist_android/MemoryActivity.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/adapter/MemoryAdapter.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/FeedMemoryFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/Memory.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/Text.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/ws/GsonArrayRequest.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/ws/MemoristApi.java
Labels: Development, Enhancement, Low priority, Review needed

#135 Android/reorder api functions
  memorist-android/app/src/main/java/com/memorist/memorist_android/MemoryActivity.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/adapter/MemoryAdapter.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/CreateMemoryFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/ProfileFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/RecommendationsFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/SearchMemoryFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/helper/JSONHelper.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/helper/UriPathHelper.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/ws/MemoristApi.java
  memorist-android/app/src/main/res/layout/fragment_create_memory.xml
  memorist-android/app/src/main/res/values/strings.xml
Labels: Development, High priority, Review needed

#163 Android/email verification check
  memorist-android/app/src/main/java/com/memorist/memorist_android/RegisterLoginActivity.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/User.java
Labels: Enhancement, Low priority

#136 Android/create post progressdialog
  memorist-android/app/src/main/java/com/memorist/memorist_android/BaseActivity.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/MemoryActivity.java
Labels: Enhancement, Low priority

#164 Android/new memory object
  memorist-android/app/src/main/java/com/memorist/memorist_android/adapter/MemoryAdapter.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/Memory.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/Owner.java
Labels: Android, Enhancement, High priority

#165 Android/profile page
  memorist-android/app/build.gradle
  memorist-android/app/src/main/java/com/memorist/memorist_android/MemoryActivity.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/RegisterLoginActivity.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/ProfileFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/helper/Constants.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/helper/SharedPrefHelper.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/ws/MemoristApi.java
  memorist-android/app/src/main/res/drawable-xxhdpi/followers_icon.png
  memorist-android/app/src/main/res/drawable-xxhdpi/following_icon.png
  memorist-android/app/src/main/res/layout/fragment_profile.xml
  memorist-android/app/src/main/res/values/strings.xml
Labels: Android, Development, High priority

#172 Android/feed media player
  memorist-android/app/src/main/java/com/memorist/memorist_android/MemoryActivity.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/adapter/MemoryAdapter.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/CreateMemoryFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/FolloweringsFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/helper/Constants.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/ApiResultFollower.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/ApiResultFollowing.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/Memory.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/Time.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/ws/MemoristApi.java
  memorist-android/app/src/main/res/drawable-xxhdpi/video_play_icon.png
  memorist-android/app/src/main/res/layout/fragment_create_memory.xml
  memorist-android/app/src/main/res/values/strings.xml
Labels: Android, High priority, Review needed

#176 View comments
  resources/material_kit/src/views/Components/Sections/SectionHomeTabs.jsx
Labels: Development, Frontend, High priority, Review needed

#171 Dislike memory
  resources/material_kit/src/views/Components/Sections/SectionHomeTabs.jsx
Labels: Development, Frontend, High priority, Review needed

#179 Profile page edit added
  resources/material_kit/src/views/ProfilePage/ProfilePage.jsx
Labels: Development, Frontend, High priority
