Repository bounswe/bounswe2018group4, pull requests merged in 2018-04, with the labels that each got.

#52 Add getFavorites.py
  getFavorites.py
Labels: Development, Review needed

#62 Added block_user function
  resources/TwitterAPI_Project/allAPIs/views.py
Labels: Development, Enhancement

#50 Add followUser.py
  resources/TwitterAPI_Project/TwitterAPI/post_tweet.py
  resources/TwitterAPI_Project/followList.txt
  resources/TwitterAPI_Project/followUser.py
Labels: Development, Enhancement, High priority

#64 Adding followUser.py
  resources/TwitterAPI_Project/allAPIs/followList.txt
  resources/TwitterAPI_Project/allAPIs/followUser.py
Labels: Development, Enhancement, High priority

#58 Add followers_following.py
  resources/TwitterAPI_Project/allAPIs/view_friends_followers_list.py
Labels: Development, High priority, Review needed

#69 Initilization of front-end
  resources/TwitterAPI_Project/frontEndUI/blockuser.html
  resources/TwitterAPI_Project/frontEndUI/favs.html
  resources/TwitterAPI_Project/frontEndUI/followers.html
  resources/TwitterAPI_Project/frontEndUI/followings.html
  resources/TwitterAPI_Project/frontEndUI/followuser.html
  resources/TwitterAPI_Project/frontEndUI/posttweet.html
  resources/TwitterAPI_Project/frontEndUI/retweet.html
  resources/TwitterAPI_Project/frontEndUI/trendings.html
Labels: Development
