Repository bounswe/bounswe2018group4, pull requests merged in 2019-01, with the labels that each got.

#191 [Frontend] Pinned map on create memory page
  resources/material_kit/package.json
  resources/material_kit/src/routes/index.jsx
  resources/material_kit/src/views/Components/Sections/SectionHomeTabs.jsx
  resources/material_kit/src/views/CreateMemoryPage/CreateMemoryPage.jsx
  resources/material_kit/src/views/CreateMemoryPage/Map.jsx
  resources/material_kit/src/views/_services/post.service.js
Labels: Development, Frontend, High priority, Review needed

#188 Android/develop
  memorist-android/.idea/misc.xml
  memorist-android/app/src/main/java/com/memorist/memorist_android/MemoryActivity.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/adapter/CommentAdapter.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/adapter/MemoryAdapter.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/adapter/UserAdapter.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/CreateMemoryFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/EditProfileFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/FeedCommentFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/ProfileFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/RecommendationsFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/fragment/SearchMemoryFragment.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/helper/Constants.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/helper/JSONHelper.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/ApiResultFollowing.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/ApiResultNoData.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/ApiResultProfile.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/Comments.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/Location.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/LocationType.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/model/Memory.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/ws/GsonArrayRequest.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/ws/MemoristApi.java
  memorist-android/app/src/main/java/com/memorist/memorist_android/ws/VolleyMultipartRequest.java
  memorist-android/app/src/main/res/drawable-xxhdpi/edit_profile.png
  memorist-android/app/src/main/res/layout/adapter_comment_row.xml
  memorist-android/app/src/main/res/layout/adapter_user_row.xml
  memorist-android/app/src/main/res/layout/fragment_create_memory.xml
  memorist-android/app/src/main/res/layout/fragment_edit_profile.xml
  memorist-android/app/src/main/res/layout/fragment_feed_comment.xml
  memorist-android/app/src/main/res/layout/fragment_profile.xml
  memorist-android/app/src/main/res/values/strings.xml
Labels: Android, Development, Enhancement, High priority

#186 [Frontend] Add time to memory
  resources/material_kit/src/views/Components/Sections/SectionHomeTabs.jsx
  resources/material_kit/src/views/CreateMemoryPage/CreateMemoryPage.jsx
  resources/material_kit/src/views/_services/post.service.js
Labels: Frontend, High priority, Review needed

#189 [Frontend] Clickable search result
  resources/material_kit/src/routes/index.jsx
  resources/material_kit/src/views/Components/Sections/SectionHomeTabs.jsx
  resources/material_kit/src/views/Components/Sections/SectionSearchTabs.jsx
  resources/material_kit/src/views/HomePage/HomePage.jsx
Labels: Frontend, High priority, Review needed
